apiVersion: v1
kind: Secret

metadata:
  name: pass-in-api-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: https://github.com/diogoazevedoo/pass-in-api.git